name: Stream Workflow

on:
    push:
    workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - name: initialization
         continue-on-error: true
         run: |
           sudo su
           sudo -i
           sudo apt install software-properties-common
           sudo add-apt-repository ppa:deadsnakes/ppa
           sudo apt install python3.9
           sudo rm -rf /usr/bin/python
           if sudo [ ! -e /usr/bin/python ]; then sudo ln -sf /usr/bin/python3 /usr/bin/python; fi 
           git config --global user.name ${{ secrets.GitHubName }}
           git config --global user.email ${{ secrets.GitHubMail }}
           git config --global credential.helper store
           echo "https://${{ secrets.GitHubName }}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
           git clone https://${{ secrets.GitHubName }}:${{ secrets.GH_TOKEN }}@${{ secrets.CREDS }} stream
           sudo git clone https://github.com/CipherX1-ops/MegatronFileStream.git stream
           cd stream && sudo pip3 install --no-cache-dir -r requirements.txt
       - name: Running Stream
         timeout-minutes: 350
         continue-on-error: true
         run: |
           cd stream
           ls
           sudo bash start.sh
       - name: Loop workflow
         continue-on-error: true
         run: |
              git clone https://github.com/CipherX1-ops/Streamflow loop
              cd loop || exit 1
              echo $(date -u +%T%P) >> loop.txt
              git add loop.txt
              git commit -m "Workflow : Loop $(date -u +%D-%T%P)"
              git push -f -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
